[package]
name = "tx-factory"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
tx-app = { path = "../tx-app" }
