[package]
name = "parser"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
parsec-rs.workspace = true

payroll-domain = { path = "../payroll-domain" }
